<a href="https://colab.research.google.com/github/kartiksharma2383/Expense_Tracker_Project_in_Python/blob/main/Expense_tracker_project_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import openpyxl
import pandas as pd
from datetime import datetime

In [2]:
df = pd.read_csv("/content/expense_data_1(Python project dataset).csv")
df

,Date,Account,Category,Subcategory,Note,INR,Income/Expense,Note.1,Amount,Currency,Account.1
0,3/2/2022 10:11,CUB - online payment,Food,NaN,Brownie,50.0,Expense,NaN,50.0,INR,50.0
1,3/2/2022 10:11,CUB - online payment,Other,NaN,To lended people,300.0,Expense,NaN,300.0,INR,300.0
2,3/1/2022 19:50,CUB - online payment,Food,NaN,Dinner,78.0,Expense,NaN,78.0,INR,78.0
3,3/1/2022 18:56,CUB - online payment,Transportation,NaN,Metro,30.0,Expense,NaN,30.0,INR,30.0
4,3/1/2022 18:22,CUB - online payment,Food,NaN,Snacks,67.0,Expense,NaN,67.0,INR,67.0
...,...,...,...,...,...,...,...,...,...,...,...
272,11/22/2021 14:16,CUB - online payment,Food,NaN,Dinner,90.0,Expense,NaN,90.0,INR,90.0
273,11/22/2021 14:16,CUB - online payment,Food,NaN,Lunch with company,97.0,Expense,NaN,97.0,INR,97.0
274,11/21/2021 17:07,CUB - online payment,Transportation,NaN,Rapido,130.0,Expense,NaN,130.0,INR,130.0
275,11/21/2021 15:50,CUB - online payment,Food,NaN,Lunch,875.0,Expense,NaN,875.0,INR,875.0
276,11/21/2021 13:30,CUB - online payment,Other,NaN,Got from gobi,2000.0,Income,NaN,2000.0,INR,2000.0

In [3]:
class ExpenseTracker:
  def __init__(self):
    self.expenses = []
    self.categories = {'Date','Account','Category','Subcategory','Note','INR', 'Income/Expense', 'Note.1', 'Amount', 'Currency', 'Account.1'}

  def add_expense(self, date, account, category, subcategory, note, inr, income_expense, note1, amount, currency, account1):
    expense = {'Date': date, 'Account': account, 'Category': category, 'Subcategory': subcategory, 'Note': note, 'INR': inr, 'Income_expense': income_expense, 'Note1': note1, 'Amount': amount, 'Currency': currency, 'Account1': account1}
    self.expenses.append(expense)

  def edit_expense(self, index, date, account, category, subcategory, note, inr, income_expense, note1, amount, currency, account1):
    if 0 <= index < len(self.add_expenses):
      self.expenses[index] = {'Date': date, 'Account': account, 'Category': category, 'Subcategory': subcategory, 'Note': note, 'INR': inr, 'Income_expense': income_expense, 'Note1': note1, 'Amount': amount, 'Currency': currency, 'Account1': account1}
    else:
      print("Invalid expense index")

  def delete_expense(self, index):
    if 0 <= index < len(self.expenses):
      del self.expenses[index]
    else:
      print("Invalid expense index.")

  def add_category(self, category, subcategory):
    if category not in self.categories:
      self.categories[category] = []
    self.categories[category].append(subcategory)

  def export_to_excel(self, filename):
    workbook = openpyxl.Workbook()
    sheet = workbook.active
    sheet.append(['Date', 'Account', 'Category', 'Subcategory', 'Note', 'INR', 'Income/Expense', 'Note.1', 'Amount', 'Currency', 'Account.1'])

    for expense in self.expenses:
      sheet.append([expense['Date'], expense['Account'], expense['Category'], expense['Subcategory'], expense['Note'], expense['INR'], expense['Income_expense'], expense['Note1'], expense['Amount'], expense['Currency'], expense['Account1']])
      workbook.save(filename)
      print(f'Expenses exported to {filename}.')

    def summary(self):
      total_spending = sum(expense['Amount'] for expense in self.expenses)
      print(f'Total spending: INR {total_spending:.2f}')
      category_spending = {category: sum(expense['Amount'] for expense in self.expenses if expense['Category'] == category) for category in set(expense['Category'] for expense in self.expenses)}
      print('Category spending:')

In [4]:
if __name__ == '__main__':
  expense_tracker = ExpenseTracker()
  while True:
    print('\nExpense Tracker Menu:')
    print('1. Add Expense')
    print('2. Edit Expense')
    print('3. Delete Expense')
    print('4. Add Category')
    print('5. Export to Excel')
    print('6. Summary')
    print('7. Quit')
    choice = input("enter your choice: ")

    if choice == '1':
      date = input('Enter date (YYYY-MM-DD): ')
      account = input('Enter account: ')
      category = input('Enter category: ')
      subcategory = input('Enter subcategory: ')
      note = input('Enter note: ')
      inr = input('Enter INR: ')
      income_expense = input('Enter Income/Expense: ')
      note1 = input('Enter Note1: ')
      amount = float(input('Enter amount: '))
      currency = input('Enter currency: ')
      account1 = input('Enter Account1: ')
      expense_tracker.add_expense(date, account, category, subcategory, note, inr, income_expense, note1, amount, currency, account1)
      print('Expense added successfully.')

    elif choice == '2':
      index = int(input('Enter expense index to edit: '))
      date = input('Enter new date (YYYY-MM-DD): ')
      account = input('Enter new account: ')
      category = input('Enter new category: ')
      subcategory = input('Enter new subcategory: ')
      note = input('Enter new note: ')
      inr = input('Enter new INR: ')
      income_expense = input('Enter new Income/Expense: ')
      note1 = input('Enter new Note1: ')
      amount = float(input('Enter new amount: '))
      currency = input('Enter new currency: ')
      account1 = input('Enter new Account1: ')
      expense_tracker.edit_expense(index, date, account, category, subcategory, note, inr, income_expense, note1, amount, currency, account1)
      print('Expense edited successfully.')

    elif choice == '3':
      index = int(input('Enter expense index to delete: '))
      expense_tracker.delete_expense(index)
      print('Expense deleted successfully.')

    elif choice == '4':
      category = input('Enter category: ')
      subcategory = input('Enter subcategory: ')
      expense_tracker.add_category(category, subcategory)
      print('Category added successfully.')

    elif choice == '5':
      filename = input('Enter filename for export (e.g., expenses.xlsx): ')
      expense_tracker.export_to_excel(filename)

    elif choice == '6':
      expense_tracker.summary()

    elif choice == '7':
      print('Exiting Expense Tracker.')
      break

    else:
      print('Invalid choice. Please try again.')

# This project is a simple expense tracker application. It allows users to:
# 1) Add new expenses with details like date, account, category, amount, etc.
# 2) Edit existing expense entries.
# 3) Delete expense entries.
# 4) Add new categories and subcategories for expenses.
# 5) Export the recorded expenses to an Excel file.
# 6) View a summary of the total spending and spending by category (although the summary function in the provided code is incomplete).

Expense Tracker Menu:
1. Add Expense
2. Edit Expense
3. Delete Expense
4. Add Category
5. Export to Excel
6. Summary
7. Quit
enter your choice: 1
Enter date (YYYY-MM-DD): 3/2/2022
Enter account: 50.0
Enter category: Food
Enter subcategory: NaN
Enter note: NaN
Enter INR: 50.0
Enter Income/Expense: Expense
Enter Note1: NaN
Enter amount: 50.0
Enter currency: INR
Enter Account1: 50.0
Expense added successfully.

Expense Tracker Menu:
1. Add Expense
2. Edit Expense
3. Delete Expense
4. Add Category
5. Export to Excel
6. Summary
7. Quit
enter your choice: 3
Enter expense index to delete: 3
Invalid expense index.
Expense deleted successfully.

Expense Tracker Menu:
1. Add Expense
2. Edit Expense
3. Delete Expense
4. Add Category
5. Export to Excel
6. Summary
7. Quit
enter your choice: 5
Enter filename for export (e.g., expenses.xlsx): expenses.xlsx
Expenses exported to expenses.xlsx.

Expense Tracker Menu:
1. Add Expense
2. Edit Expense
3. Delete Expense
4. Add Category
5. Export to Excel
6. Summary
7. Quit
enter your choice: 7
Exiting Expense Tracker.